name: Docker Image CI

on:
  push:
    branches: [ php8.1 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag php-apache-extended:8.1.3
